# server endpoint
server.port=8444
server.ssl.enabled=true
server.ssl.client-auth=need
server.ssl.key-store-type=PKCS12

# server keystore
server.ssl.keyAlias=portfolio-manager-server
server.ssl.key-store=config/pm-server-keystore.p12
server.ssl.key-store-password=server-ks-pw
server.ssl.trust-store=config/pm-server-truststore.p12
server.ssl.trust-store-password=server-ts-pw

# internals
logging.level.root=INFO
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
spring.mvc.problemdetails.enabled=true

# auditor
auditor.key=a

# restrictions
supported.file.suffixes=json,xml,xls,xlsx
supported.file.modifiers=initial,resolved,scanned,curated,report

# storage path
storage.path=.portfolio-management-workspace
