## server endpoint
service.url=https://localhost:8444

## keystore
key.store=config/pm-client-TEST-keystore.p12
key.store.password=client-TEST-ks-pw

## truststore
trust.store=config/pm-client-TEST-truststore.p12
trust.store.password=client-TEST-ts-pw

## logging
logging.level.root=WARN

## internal
spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=true
spring.main.web-application-type=NONE

#spring.shell.command.help.grouping-mode=flat
spring.shell.script.enabled=true

spring.profiles.active=default
